# Generated by Django 4.1.5 on 2023-01-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApplication', '0003_alter_hoteluser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteluser',
            name='image',
            field=models.CharField(max_length=1000000),
        ),
    ]
