# Generated by Django 4.1.5 on 2023-01-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApplication', '0004_alter_hoteluser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteluser',
            name='email',
        ),
        migrations.AddField(
            model_name='hoteluser',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
